server:
  port: ${PORT}

lavalink:
  server:
    password: "youshallnotpass"

plugins: []

metrics:
  prometheus:
    enabled: false

sentry:
  dsn: ""

logging:
  level:
    root: INFO

server:
  address: 0.0.0.0
